- src/components/Layout/PageFooter.vue
> フッターの表示年を変更した

- .github/workflows/release.yaml
主にtraQ_S-UIの実装を参考にしました
一部不要な環境変数の削除や、コメントの追加を行っています
ref: https://github.com/traPtitech/traQ_S-UI/blob/master/.github/workflows/release.yml
> リリース用ワークフローの作成

- src/components/User/AccountList.vue
- src/components/User/AccountListItem.vue
- src/components/User/UserDetailContainer.vue
close https://github.com/traPtitech/traPortfolio-UI/issues/136
> traPブログへのリンクを追加

- src/pages/UserPage.vue
close https://github.com/traPtitech/traPortfolio-UI/issues/151
/users/:uuidを/users/:uidにしたのと、ユーザー関連のデータを直列で取得してたのを並列で取得できるように
before
after
> ユーザーページの改善

- src/components/Layout/PageHeader.vue
- src/types/shims-svg.d.ts
> 本番ビルドでヘッダーのロゴが表示できてない

- src/components/Search/UserList.vue
- src/components/Search/UserListItem.vue
- src/pages/SearchPage.vue
検索結果で「チームメンバー」って文字があって、ContestTeamのコンポーネントを検索結果ページで使ってるのがよくなかったため、新しく別で作成
___
Enhancement
___
- 検索ページ用の新しいユーザー一覧コンポーネントを作成し、既存のコンポーネントを置換しました。
- ユーザーリストアイテムコンポーネントを新規作成し、ユーザーアイコンと名前を表示する機能を追加しました。
- 検索ページで使用するメンバーリストコンポーネントを`ContestTeam`から`Search`に変更しました。
___
<tr>
<td>
<details>
<summary><strong>UserList.vue</strong><dd><code>検索ページ用のユーザー一覧コンポーネントを新規作成</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/components/Search/UserList.vue
- 新しいユーザー一覧コンポーネントを作成
- …
> 検索ページ用ユーザー一覧を作成して置換

- openapitools.json
- package-lock.json
- package.json
close #173
___
dependencies
___
- `@openapitools/openapi-generator-cli`パッケージを削除しました。
- `package-lock.json`から関連する依存関係を削除しました。
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>package-lock.json</strong><dd><code>不要な依存関係の削除</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
package-lock.json
- `@openapitools/openapi-generator-cli`の削除
- 関連する依存関係の削除
</details>
</td> …
> 不要になったのでopenapitoolsを削除

- src/components/Search/UserListItem.vue
Bug fix
___
- ユーザー検索結果画面からユーザーページに飛べない問題を修正
- `router-link`の`to`属性を`member.id`から`member.name`に変更
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>UserListItem.vue</strong><dd><code>`router-link`の`to`属性を修正</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/components/Search/UserListItem.vue
- `router-link`の`to`属性を`member.id`から`member.name`に変更
</details>
</td>
<td><a href="https://github.com/traPtitech/traPortfolio-UI/pull/186/files#diff-6b237bcf82ce3e780d …
> ユーザー検索結果画面からユーザーページに飛べない問題の改善

- src/components/User/ContestsContainer.vue
確認お願いします〜
変更前
変更後のデザインは以下のとおりです
close #192
___
Enhancement
___
- コンテストチームの複数表示に対応し、各チームの名前と結果を表示するように変更
- コンテスト名を`<h4>`タグに変更し、視覚的な階層を明確化
- CSSスタイルを微調整し、リンクのマージンと詳細情報のインデントを改善
___
<tr>
<td>
<details>
<summary><strong>ContestsContainer.vue</strong><dd><code>コンテストチームの複数表示とスタイル調整</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/components/User/ContestsContainer.vue
- コンテストチームの複数表示に対応
- コンテスト名を`<h4>`タグに変更
- CSSスタイルの微調整 …
> コンテストチームの複数表示に対応

- src/components/User/BioContainer.vue
Enhancement
___
- `BioContainer.vue` のスタイルに `white-space: pre-wrap` を追加し、ユーザーの説明が複数行に対応できるように修正。
___
<tr>
<td>
<details>
<summary><strong>BioContainer.vue</strong><dd><code>スタイルに `white-space: pre-wrap` を追加</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/components/User/BioContainer.vue
- `white-space: pre-wrap` を追加
- スタイルの修正
</details>
</td>
<td><a href="https://github.com/traPtitech/traPortfolio-UI/pull/196/files#diff-50bd6fe88d9d9777e8880c8039e492b56d1a83fffb1b4b92e375e46b9b1f4948">+1/-0</a>&nbsp; &nbsp; …
> user の description を複数行に対応させた

- src/components/Search/UserList.vue
- src/pages/SearchPage.vue
close #191
___
Bug fix
___
- `src/components/Search/UserList.vue`で、`query`プロパティを追加し、APIからユーザーを動的に取得する`fetchUsers`関数を実装。
- `src/pages/SearchPage.vue`で、`user-list`コンポーネントに`query`プロパティを渡すように変更し、ユーザーの取得ロジックを削除。
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>UserList.vue</strong><dd><code>ユーザーリストの動的更新を実装</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/components/Search/UserList.vue …
> 検索結果画面で2回目以降の検索が反映されるように修正

- src/pages/ContestTeamPage.vue
close #190
___
enhancement
___
- `external-link` コンポーネントに `v-if` ディレクティブを追加し、`contestTeamDetail.link` が存在する場合のみリンクを表示するように変更。
___
<tr>
<td>
<details>
<summary><strong>ContestTeamPage.vue</strong><dd><code>リンクが指定されていない場合の表示制御を追加</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/pages/ContestTeamPage.vue
<li><code>external-link</code> コンポーネントに <code>v-if</code> ディレクティブを追加<br> <li> <code>contestTeamDetail.link</code> が存在する場合のみリンクを表示<br> …
> リンクが指定されていないときに表示されないようにした

- package-lock.json
- package.json
- src/components/UI/AIcon.vue
- src/main.ts
- vite.config.ts
close #200
___
Enhancement, Dependencies
___
- `@iconify/vue`を使用するようにアイコンコンポーネントをリファクタリングしました。
- 不要な`@purge-icons/generated`のインポートを削除しました。
- `vite-plugin-purge-icons`を削除し、Vite設定を簡素化しました。
- パッケージ依存関係を更新し、不要なパッケージを削除しました。
___
<tr>
<td>
<details>
<summary><strong>AIcon.vue</strong><dd><code>`@iconify/vue`を使用したアイコンコンポーネントのリファクタリング</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/components/UI/AIcon.vue
- `@iconify/vue`を使用するように変更
- `computed`スタイルの削除
- `Icon`コンポーネントの使用
</details>
</td>
<td><a href="https://github.com/traPtitech/traPortfolio-UI/pull/201/fil …
> iconifyのアップデート

- src/components/User/GroupsContainer.vue
- src/pages/IndexPage.vue
close https://github.com/traPtitech/traPortfolio-UI/issues/188
___
enhancement
___
- `GroupList`コンポーネントのインポートをコメントアウトし、班が未実装であることを示すメッセージを追加しました。
- `IndexPage.vue`において、班一覧が今後実装予定であることを示すメッセージを追加し、既存の班表示ロジックをコメントアウトしました。
___
<tr>
<td>
<details>
<summary><strong>GroupsContainer.vue</strong><dd><code>班が未実装であることを示すメッセージの追加</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/components/User/GroupsContainer.vue …
> 班が未実装であることを表示

- package-lock.json
Vulnerabilities High に対応するために `npm run audit` を実行した
___
dependencies
___
- 複数の依存関係を更新し、セキュリティの脆弱性に対応しました。
- `@rollup/rollup-*` のバージョンを 4.21.3 から 4.24.0 に更新しました。
- `@types/estree` のバージョンを 1.0.5 から 1.0.6 に更新しました。
- `@volar/language-core`、`@volar/source-map`、`@volar/typescript` のバージョンを 2.4.0-alpha.5 から 2.4.6 に更新しました。
- `vue-tsc` のバージョンを 2.0.24 から 2.1.6 に更新しました。
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>package-lock.json</strong><dd><code>Update multiple dependencies to address vulnerabilities</code>&nbsp; &nbsp; </dd></summary>
<hr>
package-lock.json
<li><code>@rollup/rollup-*</code> dependencies updated from version 4.21.3 to 4.24.0.<br> <li> …
> update some dependencies

- index.html
- src/components/Layout/PageFooter.vue
- src/pages/IndexPage.vue
大学統合に伴う名称変更に対応しました
___
enhancement
___
- 大学名を「東京工業大学」から「東京科学大学」に変更しました。
- `src/pages/IndexPage.vue`と`index.html`の説明文を更新しました。
- ポートフォリオサービスのメタデータを修正しました。
___
<tr>
<td>
<details>
<summary><strong>IndexPage.vue</strong><dd><code>大学名の変更に伴うポートフォリオ説明の更新</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/pages/IndexPage.vue
- 大学名を「東京工業大学」から「東京科学大学」に変更
- ポートフォリオの説明文を更新
</details>
</td>
<td><a …
> replace: our University name

- .github/workflows/preview.yaml
確認お願いします〜
`release.yaml` と同じ方法に変更しただけなのでチェックは簡単だと思います
___
enhancement
___
- 新しいジョブ `genApi` を追加し、API生成をDockerビルドから分離しました。
- `genApi` ジョブでAPIを生成し、生成されたAPIをアーティファクトとしてアップロードするようにしました。
- `build-preview-image` ジョブで生成されたAPIをダウンロードして使用するように変更しました。
- `build-preview-image` ジョブが `genApi` ジョブに依存するように設定し、ビルドプロセスを改善しました。
___
<tr>
<td>
<details>
<summary><strong>preview.yaml</strong><dd><code>API生成ステップを追加し、ビルドプロセスを改善</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …
> fix: added genApi step before build image

- src/components/User/ContestsContainer.vue
- src/components/User/ProjectsContainer.vue
fix #205
___
Enhancement
___
- ユーザーの実績が登録されていない場合の表示メッセージを更新しました。
- ユーザーが参加したプロジェクトが登録されていない場合の表示メッセージを更新しました。
___
<tr>
<td>
<details>
<summary><strong>ContestsContainer.vue</strong><dd><code>Update message for unregistered achievements</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/components/User/ContestsContainer.vue
- Updated message for when no achievements are registered.
</details>
</td>
<td><a href="https://github.com/traPtitech/traPortfolio-UI/pull/245/files#diff-91c7589f0645d5676c70ea9984b81e71f313fb7e78c94b22cd83b60b4dce7420">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …
> ユーザーの情報が入力されていないときの表示を修正

- src/components/Project/MemberList.vue
close #224
___
Enhancement
___
- プロジェクトメンバーを加入日昇順にソートするためのロジックを追加。
- `computed`プロパティ`sortedMembers`を作成し、`year`と`semester`を基準にメンバーをソート。
- テンプレート内で`v-for`ディレクティブを`sortedMembers`に変更し、ソートされたリストを表示。
___
<tr>
<td>
<details>
<summary><strong>MemberList.vue</strong><dd><code>メンバーリストを加入日昇順にソートするロジックを追加</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/components/Project/MemberList.vue
<li>新しい<code>computed</code>プロパティ<code>sortedMembers</code>を追加し、メンバーを加入日昇順にソート。<br> …
> プロジェクトメンバーを加入日昇順にソート

- src/components/Project/MemberList.vue
#255 で指摘を受けた点の修正です
___
Enhancement
___
- `computed`プロパティ`sortedMembers`を修正し、`toSorted()`メソッドを使用してメンバーを加入日昇順にソート。
- ソートロジックを`year`と`semester`に基づいて実装。
- `v-for`ディレクティブで`members`の代わりに`sortedMembers`を使用することで、ソートされたリストをテンプレートに表示。
___
<tr>
<td>
<details>
<summary><strong>MemberList.vue</strong><dd><code>メンバーリストを加入日昇順にソートするロジックの修正</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/components/Project/MemberList.vue …
> ソート時にtoSorted()を使用

- package-lock.json
脆弱性の表示が出ていたのでコマンドを走らせました
ご確認をお願いします！
___
dependencies
___
- `npm audit fix` was executed to address vulnerabilities in the dependencies.
- Updated the following dependencies in `package-lock.json`:
- `@eslint/plugin-kit` from 0.2.1 to 0.2.4.
- `cross-spawn` from 7.0.3 to 7.0.6.
- `nanoid` from 3.3.7 to 3.3.8.
- Ensures the project uses the latest secure and compatible versions of these packages.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>package-lock.json</strong><dd><code>Updated dependencies to address vulnerabilities and ensure </code><br><code>compatibility.</code></dd></summary>
<hr>
package-lock.json
<li>Updated the version of …
> ran `npm audit fix`

- src/mocks/users.ts
バックエンドリポジトリにある API スキーマの変更に追従した変更
___
Enhancement
___
- `prPermitted` フィールドを全てのアカウントから削除
- API スキーマの変更に追従
___
<tr>
<td>
<details>
<summary><strong>users.ts</strong><dd><code>`prPermitted` フィールド削除</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/mocks/users.ts
- `prPermitted` フィールドを削除
- サンプルアカウントデータの簡素化
</details>
</td>
<td><a href="https://github.com/traPtitech/traPortfolio-UI/pull/281/files#diff-225da787a88cf24fcbe3cad2104597 …
> `prPermitted` フィールドの削除

- src/pages/SearchPage.vue
- src/pages/UserPage.vue
- src/router/index.ts
変更したページタイトルを仮で「部員一覧」としましたが、ランダムで一部を取り出しただけなので他の表現に変えた方が良い気がしています
___
Bug fix, Enhancement
___
- クエリパラメータが未設定の場合に空文字列を設定し、表示を「部員一覧」に変更しました。
- パンくずリストのリンクを 'UserSearch' から 'Users' に修正しました。
- `/users` のルート定義をリダイレクトから新しいコンポーネントに変更し、新しいルート名 'Users' を追加しました。
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>SearchPage.vue</strong><dd><code>クエリパラメータ未設定時の処理と表示の修正</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/pages/SearchPage.vue
- 修正: …
> リダイレクトを修正し、クエリパラメータが空の場合の表示を変更した

- .github/workflows/pr-agent.yaml
以下のPRと同じ変更です
https://github.com/traPtitech/traPortfolio-Dashboard/pull/451
> API keyの利用時にproxyを利用する
