traPtitech/traPortfolio-UI

package-lock.json
src/components/Project/MemberList.vue
src/components/Project/MemberListItem.vue
src/pages/Project.vue

プロジェクトの詳細画面の実装
- プロジェクト名の表示
- プロジェクトの紹介リンクの表示
- プロジェクトメンバーのハンドルネームと本名の表示
- プロジェクトメンバーのアイコンを仮表示

プロジェクトページ #17

---

src/components/Index/GroupNameList.vue
src/components/Index/RecentList.vue
src/components/Layout/SectionTitle.vue
src/components/UI/SearchInputLarge.vue
src/pages/Index.vue

Indexページの作成

---

src/components/ContestTeam/MemberListItem.vue
src/components/Event/HostnameListItem.vue
src/components/Group/MemberListItem.vue
src/components/Project/MemberListItem.vue
src/components/UI/UserIcon.vue
src/components/User/UserDetailContainer.vue

close https://github.com/traPtitech/traPortfolio-UI/issues/86

usericonの共通化

---

index.html
src/index.scss

close https://github.com/traPtitech/traPortfolio-UI/issues/90

フォントをfigmaに合わせた

---

.github/dependabot.yml

Dashboard同様の設定を反映

---

src/consts/services.ts

TwitterをXに変更した

---

src/components/UI/SearchInput.vue

検索ボックスが空欄の時にEnterを押しても飛ばないようにした

---

src/components/User/ContestsContainer.vue
src/components/User/GroupsContainer.vue
src/components/User/ProjectsContainer.vue

close https://github.com/traPtitech/traPortfolio-UI/issues/143

参加プロジェクトとかがないときの表示

---

src/components/Layout/PageContainer.vue

spで表示が微妙にならないようにpadding追加

---

src/pages/IndexPage.vue

Kaggleが入ってないとかあったので、https://trap.jp/about/ の説明文に修正

トップページのテキスト変更

---

.github/workflows/main.yml
.github/workflows/release.yaml
.github/workflows/staging.yml
Dockerfile

一旦やってみました
各jobの手前にAPIからのtsファイル自動生成部分を書き足して実装しています

最終のDockerfileからAPIからの自動生成部分を分離

---

.dockerignore
.github/workflows/main.yml
.github/workflows/release.yaml
.github/workflows/staging.yml
Dockerfile
package.json
scripts/generateApi.js

APIからの自動生成周り・Docker・workflowを一括で修正

---

Dockerfile

NODE_ENVの設定場所を修正

---

src/components/ContestTeam/MemberListItem.vue
src/components/Event/HostnameListItem.vue
src/components/Group/AdminListItem.vue
src/components/Group/MemberListItem.vue
src/components/Project/MemberListItem.vue

`/user`以下のパスがtraQUIDになったのに合わせてリンクも修正

---

src/components/Contest/ContestTeamListItem.vue
src/components/ContestTeam/MemberListItem.vue
src/components/Event/HostnameListItem.vue
src/components/Group/AdminListItem.vue
src/components/Group/MemberListItem.vue
src/components/Project/MemberListItem.vue
src/components/UI/UserIcon.vue
src/components/UI/UserIcons.vue
src/components/User/UserDetailContainer.vue

メインの部分は`src/components/Contest/ContestTeamListItem.vue`でidをnameにしたところ
あとは[dashboardで前に修正したやつ](https://github.com/traPtitech/traPortfolio-Dashboard/pull/285)に合わせてuserIdをuserNameにした

userIconsのURLがidのままだったのでnameにした

---

.github/workflows/pr-agent.yaml

こちらも確認お願いします！
___
enhancement
___
- `PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS`に「Please use Japanese in descriptions.」を追加し、日本語対応を強化
___
<tr>
<td>
<details>
<summary><strong>pr-agent.yaml</strong><dd><code>`PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS`の日本語対応</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/pr-agent.yaml
- `PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS`に日本語での説明を追加
</details>
</td>
<td><a href="https://github.com/traPtitech/traPortfolio-UI/pull/185/files#diff-74cc68580425f6daeaef927a1a277fa13114d41479d6d4caab2975ca795585a0">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …

サジェストを日本語に

---

package-lock.json
package.json

dashboard 同様
___
enhancement, configuration changes
___
- `package.json`の`dev`スクリプトから`concurrently`を削除し、`vite`のみを実行するように簡素化しました。
- この変更により、開発環境の設定が簡略化され、依存関係が減少します。
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Simplify development script in package.json</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
package.json
<li>Removed <code>concurrently</code> from the <code>dev</code> script.<br> <li> Simplified <code>dev</code> script to only run <code>vite</code>.<br>
</details>
</td>
<td><a …

delete: prism

---

.prettierrc
eslint.config.js
src/App.vue
src/components/Contest/ContestTeamListItem.vue
src/components/ContestTeam/MemberListItem.vue
src/components/Event/HostnameListItem.vue
src/components/Events/EventList.vue
src/components/Group/AdminList.vue
src/components/Group/AdminListItem.vue
src/components/Group/MemberListItem.vue
src/components/Groups/GroupList.vue
src/components/Index/TopSection.vue
src/components/Layout/BreadCrumbTrail.vue
src/components/Layout/PageContainer.vue
src/components/Layout/PageFooter.vue
src/components/Project/MemberListItem.vue
src/components/Search/UserListItem.vue
src/components/UI/AIcon.vue
src/components/UI/ExternalLink.vue
src/components/UI/SearchInput.vue
src/components/User/AccountList.vue
src/components/User/AccountListItem.vue
src/components/User/ContestsContainer.vue
src/components/User/EventsContainer.vue
src/components/User/ProjectsContainer.vue
src/components/User/UserDetailContainer.vue
src/pages/GroupPage.vue
src/pages/IndexPage.vue
src/pages/ProjectPage.vue

commit メッセージの通り
___
enhancement, configuration changes
___
- ESLintとPrettierの設定を更新し、Vueコンポーネントのフォーマットを改善しました。
- 各Vueファイルでコンポーネントの属性を1行に1つずつ配置するように変更しました。
- ESLintの設定にHTMLの自己閉じタグとインデントに関する新しいルールを追加しました。
- Prettierの設定に`singleAttributePerLine`オプションを追加しました。
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>27 files</summary><table>
<tr>
<td>
<details>
<summary><strong>App.vue</strong><dd><code>Format `router-view` component for better readability</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/App.vue
- Adjusted formatting for `router-view` component.
</details>
</td>
<td><a href="https://github.com/traPtitech/traPortfolio-UI/pull/234/files#diff-7a7a37b12ee1265d7e27577ec286120d2cbc094 …

fix: ESLint と Prettier の競合を解消した (Prettier に寄せた)

---

src/consts/services.ts
src/mocks/users.ts

close #256
___
Enhancement, Tests
___
- Blueskyアカウントタイプを追加
- services.tsにBlueskyサービス定義を追加
- mocks/users.tsにBlueskyモックアカウント追加
___
<details> <summary><h3> File Walkthrough</h3></summary>
<tr>
<td>
<details>
<summary><strong>services.ts</strong><dd><code>Blueskyサービス定義追加</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/consts/services.ts …

accountTypeにblueskyを追加

---

public/mockServiceWorker.js
src/components/User/AccountList.vue
src/components/User/AccountListItem.vue
src/mocks/users.ts

close [#204](https://github.com/traPtitech/traPortfolio-UI/issues/204)
- src/components/User/AccountList.vue
traPのアイコンにtittle属性（traP : ユーザー名）を追加しました。~~traQが間違えてtraPになっていることにコミット後に気づいたのでひとまずdraft pull requestにしておきました。~~ (錯乱してただけでtraPが正しいです)
- src/components/User/AccountListItem.vue
外部SNS等のアイコンについてtittle属性（サイト名 : 外部ユーザー名）を追加しました。
- src/mocks/users.tsでは
外部アカウント名が存在しないときにはtittle属性が設定されないということを確かめるために、atcoder,blog,ctftimeのみに外部ユーザー名としてsampleAccountを与えました。ここのpushはいらない気がしますがどのようにすればよろしいでしょうか？
- public/mockServiceWorker.js
手を加えた記憶がないのに多くの変更があるのは途中でmainからpullしたからでしょうか？正直、よくわかっていません
___
Enhancement
___
- アイコンにサービス名と表示名のtitle属性追加
- traPアイコンでユーザー名表示
- 外部サービスアイコンでサービス名表示
- モックユーザーデータにdisplayName設定
- MSWワーカーのバージョン更新とシリアライズ改善
___
<details> <summary><h3> File Walkthrough</h3></summary> …

feat.アイコンのマウスホバー時にサービス名と外部アカウント名を表示
